# Generated by Django 2.2.11 on 2020-04-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_donation_is_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
